version: 0.2
env:
  variables:
    SECRET: "your_secret_value"
    DB_HOST: "localhost:27017"
    DB_USER: ""
    DB_PASS: ""
    DB_NAME: "yum-food"
    DB_EXTENSION: "+srv://"
    NODE_ENV: "development"
    API_KEY: ""
    CLOUDINARY_CLOUD_NAME: ""
    CLOUDINARY_API_KEY: ""
    CLOUDINARY_API_SECRET: ""
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - npm run heroku-postbuild
      - npm prune --production
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - node_modules
